import Head from "next/head";
import type { NextPage } from "next";

import { SignOutButton } from "@clerk/nextjs";
import { useDashboard } from "~/hooks/pages/useDashboard";

export const Dashboard: NextPage = () => {
  const { user, isLoaded, signOutCallback } = useDashboard();

  if (!isLoaded) return <div>Loading...</div>;
  if (!user) return <div>Error: Not logged in</div>;

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Dashboard</h1>
        <h2>Welcome, {user.fullName}</h2>
        <SignOutButton signOutCallback={signOutCallback} />
      </main>
    </>
  );
};

export default Dashboard;
