import Head from "next/head";
import type { NextPage } from "next";
import { TaskList } from "~/components/task/taskList";
import { PageLayout } from "~/components/layout";
import { TaskCreator } from "~/components/task/taskCreator";

export const TaskPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>TaskPage</title>
        <meta name="description" content="Generated by create-t3-app" />{" "}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <div className="flex h-full">
          <div className="flex-1">
            <TaskList />
          </div>
          <div className="flex-1">
            <TaskCreator />
          </div>
        </div>
      </PageLayout>
    </>
  );
};

export default TaskPage;
